//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBRapPhimEntities : DbContext
    {
        public DBRapPhimEntities()
            : base("name=DBRapPhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ghe> ghe { get; set; }
        public virtual DbSet<lichchieu> lichchieu { get; set; }
        public virtual DbSet<nguoidung> nguoidung { get; set; }
        public virtual DbSet<phim> phim { get; set; }
        public virtual DbSet<phongchieu> phongchieu { get; set; }
        public virtual DbSet<sanpham> sanpham { get; set; }
        public virtual DbSet<theloai> theloai { get; set; }
    }
}
